version: '3.7'

services:
  db:
    image: postgres:11
    container_name: 'fastapi_postgres'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fastapi}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - fastapi_postgres:/var/lib/postgresql/data
    restart: on-failure

volumes:
  fastapi_postgres:
    external:
      true